config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users

  get '/folders/listAllFolders', to: 'folders#list_all_folders', as: 'list_folders'
  get '/mediaFiles/listAllFiles', to: 'media_files#list_all_files', as: 'list_files'

  resources :folders do
    resources :media_files, only: %i[index new create edit update destroy] do
      member do
        get :watch
      end
    end
  end

  get '/users/:id', to: 'users#show', as: 'user_profile'
  get '/serve_media_file', to: 'downloads#serve', as: 'serve_media_file'
  root to: 'home#index'
end

app/views/shared/_carousel.html.erb
<!-- Gallery Modal -->
<div class="modal fade" id="galleryModal" tabindex="-1" aria-labelledby="galleryModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="galleryModalLabel">Галерия</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Затвори"></button>
      </div>
      <div class="modal-body">
        <div id="userImagesCarousel" class="carousel slide" data-bs-ride="carousel">
          <div class="carousel-inner">
            <% if media_files.present? %>
              <% active_set = false %> <!-- Variable to track if 'active' class has been set -->
              <% media_files.each do |media_file| %>
                <% file_extension = File.extname(media_file.file).downcase %>
                <% if %w[.jpg .jpeg .png .gif].include?(file_extension) %>
                  <% file_path = File.join(Rails.configuration.user_files_path, media_file.folder.user.email, media_file.folder.full_path, media_file.file) %>
                  <% if File.exist?(file_path) %>
                    <div class="carousel-item <%= 'active' unless active_set %>">
                      <%= image_tag(serve_media_file_path(file_path: file_path), alt: media_file.file, class: 'd-block w-100') %>
                    </div>
                    <% active_set = true %> <!-- Set the 'active' class only for the first image -->
                  <% end %>
                <% end %>
              <% end %>
            <% else %>
              <p>Няма налични изображения за показване.</p>
            <% end %>
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#userImagesCarousel" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#userImagesCarousel" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_folder_tree.html.erb
<li class="list-group-item d-flex justify-content-between align-items-center" style="padding-left: <%= level * 20 %>px;">
  <div>
    <!-- Folder Icon -->
    <% if folder.parent.present? %>
      <i class="fa-solid fa-folder-child text-muted"></i> <!-- Child Folder -->
    <% else %>
      <i class="fa-solid fa-folder text-primary"></i> <!-- Parent Folder -->
    <% end %>

    <!-- Folder Name -->
    <strong><%= link_to folder.name, folder_media_files_path(folder), class: 'text-decoration-none' %></strong>
    <small class="text-muted d-block">
      - качена на <%= folder.created_at.strftime("%d/%m/%Y") %> от <%= folder.user.email %>
    </small>
    <% if @folder_sizes[folder.id] %>
      <small class="text-success"> - Размер: <%= number_to_human_size(@folder_sizes[folder.id]) %></small>
    <% end %>
  </div>

  <!-- Actions (Edit and Delete) -->
  <div>
    <span class="badge bg-primary rounded-pill"><%= folder.media_files.count %> файла</span>
    <span class="badge bg-secondary rounded-pill"><%= folder.subfolders.count %> под-папки</span>

    <%= link_to edit_folder_path(folder), class: 'btn btn-sm btn-warning ms-2' do %>
      <i class="fa fa-edit"></i> Редактиране
    <% end %>

    <%= link_to folder_path(folder), method: :delete, data: { confirm: "Сигурни ли сте, че искате да изтриете тази папка?" }, class: 'btn btn-sm btn-danger ms-2' do %>
      <i class="fa fa-trash"></i> Изтриване
    <% end %>
  </div>
</li>

<!-- Recursively Render Only Direct Subfolders -->
<% folder.subfolders.each do |subfolder| %>
  <%= render partial: 'shared/folder_tree', locals: { folder: subfolder, level: level + 1 } %>
<% end %>

app/views/shared/_media_filter.html.erb
<!-- app/views/shared/_media_filter.html.erb -->
<!-- Бутон за филтър за всички файлове -->
<%= link_to url_for(filter: nil), class: 'btn btn-outline-secondary' do %>
  <i class="fas fa-filter"></i> Всички файлове
<% end %>

<!-- Бутон за филтър за изображения -->
<%= link_to url_for(filter: 'images'), class: 'btn btn-outline-primary ml-2' do %>
  <i class="fas fa-image"></i> Снимки
<% end %>

<!-- Бутон за филтър за видеа -->
<%= link_to url_for(filter: 'videos'), class: 'btn btn-outline-info ml-2' do %>
  <i class="fas fa-video"></i> Видеа
<% end %>

app/views/shared/_top_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%= root_path %>">MediaUploaderApp</a>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ms-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to folders_path, class: 'nav-link' do %>
            <i class="fa-solid fa-folder-plus"></i> Мое Съдържание
          <% end %>
        </li>
        <!-- Линк към профила на потребителя -->
        <li class="nav-item">
          <%= link_to user_profile_path(current_user), class: 'nav-link' do %>
            <i class="fa-solid fa-user"></i> Профил
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to destroy_user_session_path, method: :delete, data: { turbo_method: :delete }, class: 'nav-link' do %>
            <i class="fa-solid fa-right-from-bracket"></i> Изход
          <% end %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to new_user_registration_path, class: 'nav-link' do %>
            <i class="fa-solid fa-user-plus"></i> Регистрирай се
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to new_user_session_path, class: 'nav-link' do %>
            <i class="fa-solid fa-door-open"></i> Вход
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>